In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("countries-aggregated.csv")

In [13]:
data.head()

         Date      Country  Confirmed  Recovered  Deaths
0  2020-01-22  Afghanistan          0        0.0       0
1  2020-01-22      Albania          0        0.0       0
2  2020-01-22      Algeria          0        0.0       0
3  2020-01-22      Andorra          0        0.0       0
4  2020-01-22       Angola          0        0.0       0

In [16]:
data[data.Country=="US"].replace("US","USA")

             Date Country  Confirmed  Recovered  Deaths
164    2020-01-22     USA          1        0.0       0
340    2020-01-23     USA          1        0.0       0
516    2020-01-24     USA          2        0.0       0
692    2020-01-25     USA          2        0.0       0
868    2020-01-26     USA          5        0.0       0
1044   2020-01-27     USA          5        0.0       0
1220   2020-01-28     USA          5        0.0       0
1396   2020-01-29     USA          5        0.0       0
1572   2020-01-30     USA          5        0.0       0
1748   2020-01-31     USA          7        0.0       0
1924   2020-02-01     USA          8        0.0       0
2100   2020-02-02     USA          8        0.0       0
2276   2020-02-03     USA         11        0.0       0
2452   2020-02-04     USA         11        0.0       0
2628   2020-02-05     USA         11        0.0       0
2804   2020-02-06     USA         11        0.0       0
2980   2020-02-07     USA         11        0.0       0
3156   2020-02-08     USA         11        0.0       0
3332   2020-02-09     USA         11        3.0       0
3508   2020-02-10     USA         11        3.0       0
3684   2020-02-11     USA         12        3.0       0
3860   2020-02-12     USA         12        3.0       0
4036   2020-02-13     USA         13        3.0       0
4212   2020-02-14     USA         13        3.0       0
4388   2020-02-15     USA         13        3.0       0
4564   2020-02-16     USA         13        3.0       0
4740   2020-02-17     USA         13        3.0       0
4916   2020-02-18     USA         13        3.0       0
5092   2020-02-19     USA         13        3.0       0
5268   2020-02-20     USA         13        3.0       0
...           ...     ...        ...        ...     ...
6500   2020-02-27     USA         58        6.0       0
6676   2020-02-28     USA         60        7.0       0
6852   2020-02-29     USA         68        7.0       1
7028   2020-03-01     USA         74        7.0       1
7204   2020-03-02     USA         98        7.0       6
7380   2020-03-03     USA        118        7.0       7
7556   2020-03-04     USA        149        7.0      11
7732   2020-03-05     USA        217        7.0      12
7908   2020-03-06     USA        262        7.0      14
8084   2020-03-07     USA        402        7.0      17
8260   2020-03-08     USA        518        7.0      21
8436   2020-03-09     USA        583        7.0      22
8612   2020-03-10     USA        959        8.0      28
8788   2020-03-11     USA       1281        8.0      36
8964   2020-03-12     USA       1663       12.0      40
9140   2020-03-13     USA       2179       12.0      47
9316   2020-03-14     USA       2727       12.0      54
9492   2020-03-15     USA       3499       12.0      63
9668   2020-03-16     USA       4632       17.0      85
9844   2020-03-17     USA       6421       17.0     108
10020  2020-03-18     USA       7783      105.0     118
10196  2020-03-19     USA      13677      121.0     200
10372  2020-03-20     USA      19100      147.0     244
10548  2020-03-21     USA      25489      176.0     307
10724  2020-03-22     USA      33276      178.0     417
10900  2020-03-23     USA      43847      178.0     557
11076  2020-03-24     USA      53740      348.0     706
11252  2020-03-25     USA      65778      361.0     942
11428  2020-03-26     USA      83836      681.0    1209
11604  2020-03-27     USA     101657      869.0    1581

[66 rows x 5 columns]

In [17]:
df = data.sort_values(by=['Date'],ascending=False)

In [18]:
df.to_csv("countries-aggregated.csv",index=False)